# Create a new user
POST http://localhost:4000/api/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "manunited@test.co",
  "dateBirth": "1992-02-22",
  "firstname": "Man",
  "lastname": "United",
  "password": "12345678"
}

###

# Upload avatar
PATCH http://localhost:4000/api/users/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE1NDQ5NjAzLCJleHAiOjE3MTU0NTExMDN9.Zh7S_qWQL74l-rV6SOsc277lIR4UFkE7VPQO2S6uVvU
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="default-avatar-48.png"

< ./default-avatar-48.png

--boundary--

###

# Change Password
POST http://localhost:4000/api/users/changePassword HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE1NDUwMzIyLCJleHAiOjE3MTU0NTE4MjJ9.d82kQnDSp3hVQ2rzcerGwstY-RvWbk_CT3xafDSg0eE
Content-Type: application/json

{
  "currentPassword": "222222",
  "newPassword": "999999"
}

###

# Get user by ID
GET http://localhost:4000/api/users/663244e674d85f1031cea6f3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE1MTA5OTAzLCJleHAiOjE3MTUxMTE0MDN9.vtfKJilRyyxwc4NI36M5-7Vo_14XLneYYUD1Upkw6Gc

###

# Login user by email and password
POST http://localhost:4000/api/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "myemail@test.co",
  "password": "999999"
}

###

# Get new JWT pair
POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwidG9rZW5JZCI6IjBiMzk0NDA1LWM0ZTQtNGRmMy04NGNjLTg4ZTI5YTRiOGJkZiIsImlhdCI6MTcxNDY2NDEwOSwiZXhwIjoxNzE3MjU2MTA5fQ.A_-yL6zgW1H6VJbfMzXpQvJnK5flYjpwYOZiCxybnio

###

# Get details about user (posts count, subscribers count and so on)
GET http://localhost:4000/api/users/663244e674d85f1031cea6f3/details HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE1MTA5OTAzLCJleHAiOjE3MTUxMTE0MDN9.vtfKJilRyyxwc4NI36M5-7Vo_14XLneYYUD1Upkw6Gc

###
