# Get all posts
GET http://localhost:4000/api/blog HTTP/1.1

###

# Get posts with filter

GET http://localhost:4000/api/blog?limit=2&sortDirection=desc&type=photo&page=1 HTTP/1.1

###

# Get posts by post type (video, text, quote, .etc)

GET http://localhost:4000/api/blog?type=link HTTP/1.1

###

# Sort posts by likes/comments. Deafult is by date.

GET http://localhost:4000/api/blog?sortDirection=desc&sortBy=likes HTTP/1.1

###

# Get post by Id

GET http://localhost:4000/api/blog/cfc58b27-cc04-432d-8fcc-c4bfa5fc7a34 HTTP/1.1

###

# Create a new post
POST http://localhost:4000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE0OTI2MTE5LCJleHAiOjE3MTQ5Mjc2MTl9.-iEG6sSuCAOmkO9e9jQ7GnhNX5rd_LmhG7grQaiUJrE
Content-Type: application/json

{
  "type": "link",
  "postTypeFields": {
    "link": "https://www.youtube.com/watch?v=_Z1heGTnVJM&ab_channel=InterMiamiCF",
    "description": "Inter Miami"
  }
}

###

# Delete a post by id

DELETE http://localhost:4000/api/blog/cfc58b27-cc04-432d-8fcc-c4bfa5fc7a34 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE1MTgzMzMyLCJleHAiOjE3MTUxODQ4MzJ9.9pwVE2_eNaR201jaf6XvWPnY74kI-hnB9xAR65AnVko

###

# Update a post by id

PATCH http://localhost:4000/api/blog/6d308040-96a2-4162-bea6-2338e9976540 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE1MTgzMzMyLCJleHAiOjE3MTUxODQ4MzJ9.9pwVE2_eNaR201jaf6XvWPnY74kI-hnB9xAR65AnVko

{
  "type": "video",
  "tags": ["cover", "music", "rock"],
  "postTypeFields": {
    "title": "Metallica - Enter Sandman - (Guitar Cover) 1",
    "videoUrl": "https://www.youtube.com/watch?v=91vFQExKpYQ&ab_channel=ColeRolland"
  }
}

###

# Find a post by title (only video and text posts have title)

GET http://localhost:4000/api/blog/search?title=cover HTTP/1.1
Content-Type: application/json

###

# Find posts by tagName

GET http://localhost:4000/api/blog?tagName=cover HTTP/1.1
Content-Type: application/json

###

# Find posts by userId

GET http://localhost:4000/api/blog?userId=663244e674d85f1031cea6f3 HTTP/1.1
Content-Type: application/json

###

# Get all draft posts of auth user

GET http://localhost:4000/api/blog/drafts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE1MzMxODMwLCJleHAiOjE3MTUzMzMzMzB9.wVC9EAPEfEDAuBivt7u9ikYmKYLNSgpt4dbcbs-_oj8

###

# Add like to the post

POST http://localhost:4000/api/blog/b38f7b47-e0ed-41bc-86b8-24226c5e36e3/like HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE1MTgzMzMyLCJleHAiOjE3MTUxODQ4MzJ9.9pwVE2_eNaR201jaf6XvWPnY74kI-hnB9xAR65AnVko

###

# Remove like from the post

DELETE http://localhost:4000/api/blog/b38f7b47-e0ed-41bc-86b8-24226c5e36e3/like HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE1MTgzMzMyLCJleHAiOjE3MTUxODQ4MzJ9.9pwVE2_eNaR201jaf6XvWPnY74kI-hnB9xAR65AnVko

###

# Make repost

POST http://localhost:4000/api/blog/6d308040-96a2-4162-bea6-2338e9976540/repost HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE1Mzc1NzM2LCJleHAiOjE3MTUzNzcyMzZ9.UGPo31dwRwgP_oDvP06ZaFyvUWl5vz1N53jtHrJqagk

###
