# Create a new user
POST http://localhost:3000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
  "email": "myemail@test.co",
  "dateBirth": "2012-02-22",
  "firstname": "Kurt",
  "lastname": "Cobain",
  "password": "12345678"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/663244e674d85f1031cea6f3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE0ODM0Mzg5LCJleHAiOjE3MTQ4MzU4ODl9._L2Uy2qoN6sZ4plKSWiQ9WjiPE0sn6j4yLhE51ZYIvs

###

# Login user by email and password
POST http://localhost:3000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
  "email": "myemail@test.co",
  "password": "12345678"
}

###

# Change password
POST http://localhost:3000/api/auth/changePassword HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyNDRlNjc0ZDg1ZjEwMzFjZWE2ZjMiLCJlbWFpbCI6Im15ZW1haWxAdGVzdC5jbyIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJDb2JhaW4iLCJmaXJzdG5hbWUiOiJLdXJ0IiwiaWF0IjoxNzE0NTczMzgxLCJleHAiOjE3MTQ1NzQyODF9.MHA54X9eF2hLhqmoYIg3SqMOduR60xV5hN-QL8JEYOs

{
  "currentPassword": "222222",
  "newPassword": "12345678"
}

###

# Get new JWT pair
POST http://localhost:3333/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNzA1NjgwMDA4LCJleHAiOjE3MDgyNzIwMDh9.10Jr7bWOiFTTi42JcMgPh0GVbxa2ikvn8vUVcF8d-AY

###
